// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: node.proto

#include "node.pb.h"
#include "node.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>

static const char* Miner_method_names[] = {
  "/Miner/BroadcastBlock",
  "/Miner/BroadcastTransaction",
  "/Miner/GetAddr",
  "/Miner/GetTransaction",
  "/Miner/GetBlock",
  "/Miner/GetHeartbeat",
};

std::unique_ptr< Miner::Stub> Miner::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< Miner::Stub> stub(new Miner::Stub(channel));
  return stub;
}

Miner::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_BroadcastBlock_(Miner_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BroadcastTransaction_(Miner_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAddr_(Miner_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTransaction_(Miner_method_names[3], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBlock_(Miner_method_names[4], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetHeartbeat_(Miner_method_names[5], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Miner::Stub::BroadcastBlock(::grpc::ClientContext* context, const ::Block& request, ::Success* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_BroadcastBlock_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::Success>* Miner::Stub::AsyncBroadcastBlockRaw(::grpc::ClientContext* context, const ::Block& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::Success>(channel_.get(), cq, rpcmethod_BroadcastBlock_, context, request);
}

::grpc::Status Miner::Stub::BroadcastTransaction(::grpc::ClientContext* context, const ::Transaction& request, ::Success* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_BroadcastTransaction_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::Success>* Miner::Stub::AsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::Transaction& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::Success>(channel_.get(), cq, rpcmethod_BroadcastTransaction_, context, request);
}

::grpc::Status Miner::Stub::GetAddr(::grpc::ClientContext* context, const ::AddrRequest& request, ::AddrResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_GetAddr_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::AddrResponse>* Miner::Stub::AsyncGetAddrRaw(::grpc::ClientContext* context, const ::AddrRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::AddrResponse>(channel_.get(), cq, rpcmethod_GetAddr_, context, request);
}

::grpc::Status Miner::Stub::GetTransaction(::grpc::ClientContext* context, const ::TransactionRequest& request, ::Transaction* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_GetTransaction_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::Transaction>* Miner::Stub::AsyncGetTransactionRaw(::grpc::ClientContext* context, const ::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::Transaction>(channel_.get(), cq, rpcmethod_GetTransaction_, context, request);
}

::grpc::Status Miner::Stub::GetBlock(::grpc::ClientContext* context, const ::BlockRequest& request, ::Block* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_GetBlock_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::Block>* Miner::Stub::AsyncGetBlockRaw(::grpc::ClientContext* context, const ::BlockRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::Block>(channel_.get(), cq, rpcmethod_GetBlock_, context, request);
}

::grpc::Status Miner::Stub::GetHeartbeat(::grpc::ClientContext* context, const ::EmptyRequest& request, ::Success* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_GetHeartbeat_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::Success>* Miner::Stub::AsyncGetHeartbeatRaw(::grpc::ClientContext* context, const ::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::Success>(channel_.get(), cq, rpcmethod_GetHeartbeat_, context, request);
}

Miner::Service::Service() {
  (void)Miner_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      Miner_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< Miner::Service, ::Block, ::Success>(
          std::mem_fn(&Miner::Service::BroadcastBlock), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      Miner_method_names[1],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< Miner::Service, ::Transaction, ::Success>(
          std::mem_fn(&Miner::Service::BroadcastTransaction), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      Miner_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< Miner::Service, ::AddrRequest, ::AddrResponse>(
          std::mem_fn(&Miner::Service::GetAddr), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      Miner_method_names[3],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< Miner::Service, ::TransactionRequest, ::Transaction>(
          std::mem_fn(&Miner::Service::GetTransaction), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      Miner_method_names[4],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< Miner::Service, ::BlockRequest, ::Block>(
          std::mem_fn(&Miner::Service::GetBlock), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      Miner_method_names[5],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< Miner::Service, ::EmptyRequest, ::Success>(
          std::mem_fn(&Miner::Service::GetHeartbeat), this)));
}

Miner::Service::~Service() {
}

::grpc::Status Miner::Service::BroadcastBlock(::grpc::ServerContext* context, const ::Block* request, ::Success* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Miner::Service::BroadcastTransaction(::grpc::ServerContext* context, const ::Transaction* request, ::Success* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Miner::Service::GetAddr(::grpc::ServerContext* context, const ::AddrRequest* request, ::AddrResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Miner::Service::GetTransaction(::grpc::ServerContext* context, const ::TransactionRequest* request, ::Transaction* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Miner::Service::GetBlock(::grpc::ServerContext* context, const ::BlockRequest* request, ::Block* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Miner::Service::GetHeartbeat(::grpc::ServerContext* context, const ::EmptyRequest* request, ::Success* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


